enum AVAILABILITY {
  IN_STOCK = "in-stock",
  OUT_OF_STOCK = "out-of-stock",
  LOW_STOCK = "low-stock",
}

export const products = [
  {
    name: "maggi",
    price: 430,
    qty: 43,
    thresholdValue: 12,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.IN_STOCK,
  },
  {
    name: "Bru",
    price: 257,
    qty: 23,
    thresholdValue: 12,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.IN_STOCK,
  },
  {
    name: "Red Bull",
    price: 990,
    qty: 43,
    thresholdValue: 9,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.OUT_OF_STOCK,
  },
  {
    name: "Bourn Vita",
    price: 502,
    qty: 36,
    thresholdValue: 6,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.IN_STOCK,
  },
  {
    name: "Horticks",
    price: 530,
    qty: 43,
    thresholdValue: 10,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.LOW_STOCK,
  },
  {
    name: "Ariel",
    price: 230,
    qty: 50,
    thresholdValue: 12,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.IN_STOCK,
  },
  {
    name: "Coca colo",
    price: 410,
    qty: 43,
    thresholdValue: 8,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.OUT_OF_STOCK,
  },
  {
    name: "Pepsi",
    price: 200,
    qty: 12,
    thresholdValue: 10,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.LOW_STOCK,
  },
  {
    name: "Scotch Brite",
    price: 550,
    qty: 12,
    thresholdValue: 30,
    expiryDate: "2021-03-01",
    availability: AVAILABILITY.IN_STOCK,
  },
];

export const overallInventory = {
  categories: {
    qty: 14,
    period: new Date("2024-10-24"),
  },
  topProducts: {
    qty: 888,
    totalPrice: 25000,
    period: new Date("2024-10-17"),
  },
  topSelling: {
    qty: 5,
    totalCost: 2500,
    period: new Date("2024-10-17"),
  },
  lowStocks: {
    ordered: 12,
    notInStock: 2,
    period: new Date("2024-10-17"),
  },
};

export enum ORDER_STATUS {
  DELAYED = "delayed",
  CONFIRMED = "confirmed",
  RETURNED = "returned",
  OUT_FOR_DELIVERY = "out for deleivery",
}

export const orders = [
  {
    name: "Maggi",
    orderValue: 4306,
    quantity: "43 Packets",
    orderId: 7535,
    expectedDelivery: "11-12-2022",
    onTheWay: null,
    status: ORDER_STATUS.DELAYED,
  },
  {
    name: "Bru",
    orderValue: 2557,
    quantity: "22 Packets",
    orderId: 5724,
    expectedDelivery: "21-12-2022",
    onTheWay: 9,
    status: ORDER_STATUS.CONFIRMED,
  },
  {
    name: "Red Bull",
    orderValue: 4075,
    quantity: "36 Packets",
    orderId: 2775,
    expectedDelivery: "05-12-2022",
    onTheWay: 12,
    status: ORDER_STATUS.CONFIRMED,
  },
  {
    name: "Bourn Vita",
    orderValue: 5052,
    quantity: "14 Packets",
    orderId: 2275,
    expectedDelivery: "08-12-2022",
    status: ORDER_STATUS.OUT_FOR_DELIVERY,
    onTheWay: null,
  },
  {
    name: "Horlicks",
    orderValue: 5370,
    quantity: "5 Packets",
    orderId: 2427,
    expectedDelivery: "09-01-2023",
    status: ORDER_STATUS.RETURNED,
    onTheWay: 3,
  },
  {
    name: "Harpic",
    orderValue: 6065,
    quantity: "10 Packets",
    orderId: 2578,
    expectedDelivery: "09-01-2023",
    status: ORDER_STATUS.OUT_FOR_DELIVERY,
    onTheWay: null,
  },
  {
    name: "Ariel",
    orderValue: 4078,
    quantity: "23 Packets",
    orderId: 2757,
    expectedDelivery: "15-12-2023",
    status: ORDER_STATUS.DELAYED,
    onTheWay: 9,
  },
  {
    name: "Scotch Brite",
    orderValue: 3559,
    quantity: "43 Packets",
    orderId: 3757,
    expectedDelivery: "06-06-2023",
    status: ORDER_STATUS.CONFIRMED,
    onTheWay: null,
  },
  {
    name: "Coca Cola",
    orderValue: 2055,
    quantity: "41 Packets",
    orderId: 2474,
    expectedDelivery: "11-11-2022",
    status: ORDER_STATUS.DELAYED,
    onTheWay: 5,
  },
];

export const suppliers = [
  {
    name: "Richard Martins",
    product: "Maggi",
    contact: "7687764556",
    email: "richard@gmail.com",
  },
  {
    name: "Sarah Johnson",
    product: "Salt",
    contact: "7783454567",
    email: "sarah.johnson@example.com",
  },
  {
    name: "David Lee",
    product: "Sugar",
    contact: "7678452345",
    email: "david.lee@example.com",
  },
  {
    name: "Emily Clark",
    product: "Milk",
    contact: "7789987645",
    email: "emily.clark@example.com",
  },
  {
    name: "John Doe",
    product: "Bread",
    contact: "7765434567",
    email: "john.doe@example.com",
  },
  {
    name: "Alice Brown",
    product: "Coffee",
    contact: "7684567890",
    email: "alice.brown@example.com",
  },
  {
    name: "Michael Scott",
    product: "Cheese",
    contact: "7776543210",
    email: "michael.scott@example.com",
  },
  {
    name: "Sophia Green",
    product: "Rice",
    contact: "7654345678",
    email: "sophia.green@example.com",
  },
  {
    name: "James Wilson",
    product: "Pasta",
    contact: "7656789876",
    email: "james.wilson@example.com",
  },
  {
    name: "Olivia Taylor",
    product: "Flour",
    contact: "7687544567",
    email: "olivia.taylor@example.com",
  },
  {
    name: "Ethan Harris",
    product: "Oil",
    contact: "7667890987",
    email: "ethan.harris@example.com",
  },
  {
    name: "Mia White",
    product: "Tea",
    contact: "7689098765",
    email: "mia.white@example.com",
  },
  {
    name: "Henry Lewis",
    product: "Butter",
    contact: "7645676543",
    email: "henry.lewis@example.com",
  },
];
