export enum ROUTE_CONFIG {
  LOGIN = "/auth/login",
  LOGOUT = "/logout",
  FORGOT_PASSWORD = "/auth/forgot-password",
  RESET_PASSWORD = "/auth/reset-Password",
  DASHBOARD = "/dashboard",
  INVENTORY = "/inventory",
  ADD_INVENTORY = "/inventory/add",
  PRODUCT_INFO = "/product-info",
  REPORTS = "/reports",
  SUPPLIERS = "/suppliers",
  ADD_SUPPLIERS = "/suppliers/add",
  ORDERS = "/orders",
  ADD_ORDER = "/orders/add",
  MANAGE_STORE = "/manage-store",
  ADD_STORE = "/manage-store/add",
  EDIT_STORE = "/manage-store/edit",
  SEARCH = "/search",
  SETTINGS = "/settings",
  INVENTORY_OVERVIEW = "/inventory/overview",
  INVENTORY_HISTORY = "/inventory/history",
  INVENTORY_ADJUSTMENTS = "/inventory/adjustments",
  INVENTORY_PURCHASES = "/inventory/purchases",
  EDIT_INVENTORY = "/inventory/edit",
}
