export enum ROUTE_CONFIG {
  LOGIN = "/auth/login",
  LOGOUT = "/logout",
  FORGOT_PASSWORD = "/auth/forgot-password",
  RESET_PASSWORD = "/auth/reset-Password",
  DASHBOARD = "/dashboard",
  PRODUCT_INFO = "/product-info",
  REPORTS = "/reports",
  SUPPLIERS = "/suppliers",
  NEW_SUPPLIER = "/suppliers/new-supplier",
  ORDERS = "/orders",
  NEW_ORDER = "/orders/new-order",
  MANAGE_STORE = "/manage-store",
  NEW_STORE = "/manage-store/new-store",
  EDIT_STORE = "/manage-store/edit-store",
  SEARCH = "/search",
  INVENTORY = "/inventory",
  NEW_INVENTORY = "/inventory/new-inventory",
  INVENTORY_OVERVIEW = "/inventory/overview",
  INVENTORY_HISTORY = "/inventory/history",
  INVENTORY_ADJUSTMENTS = "/inventory/adjustments",
  INVENTORY_PURCHASES = "/inventory/purchases",
  EDIT_INVENTORY = "/inventory/edit-inventory",
  SETTINGS = "/settings",
  SETTINGS_PERSONAL_INFO = "/settings/personal-info",
  SETTINGS_SECURITY = "/settings/security",
}
